-- HTTP Proxies table
CREATE TABLE IF NOT EXISTS http_proxies (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  server_id INT UNSIGNED NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  port INT UNSIGNED NOT NULL,
  status ENUM('active', 'paused', 'error', 'deleted') DEFAULT 'active',
  bytes_sent BIGINT UNSIGNED DEFAULT 0,
  bytes_received BIGINT UNSIGNED DEFAULT 0,
  last_sync_at TIMESTAMP NULL,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id),
  INDEX idx_server_id (server_id),
  INDEX idx_status (status),
  INDEX idx_deleted_at (deleted_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES vpn_servers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Translations for HTTP Proxies
INSERT INTO translations (locale, category, key_name, translation) VALUES
('en', 'common', 'sync_all', 'Sync All Stats'),
('en', 'common', 'copied', 'Copied!'),
('en', 'proxies', 'title', 'HTTP Proxies'),
('en', 'proxies', 'description', 'Manage lightweight HTTP proxies via 3proxy'),
('en', 'proxies', 'username', 'Username'),
('en', 'proxies', 'password', 'Password'),
('en', 'proxies', 'server', 'Server'),
('en', 'proxies', 'port', 'Port'),
('en', 'proxies', 'status', 'Status'),
('en', 'proxies', 'traffic', 'Traffic'),
('en', 'proxies', 'created', 'Created'),
('en', 'proxies', 'actions', 'Actions'),
('en', 'proxies', 'create', 'Create Proxy'),
('en', 'proxies', 'pause', 'Pause'),
('en', 'proxies', 'resume', 'Resume'),
('en', 'proxies', 'delete', 'Delete'),
('en', 'proxies', 'delete_confirm', 'Delete this proxy user permanently?'),
('en', 'proxies', 'no_proxies', 'No proxies yet'),
('en', 'proxies', 'generate', 'Generate'),
('en', 'proxies', 'leave_blank_auto', 'Leave blank to auto-generate'),
('en', 'form', 'select_server', 'Select Server'),
('en', 'proxies', 'active', 'Active'),
('en', 'proxies', 'paused', 'Paused'),
('en', 'proxies', 'error', 'Error'),
('en', 'menu', 'proxies', 'Proxies'),

('ru', 'common', 'sync_all', 'Синхронизировать всё'),
('ru', 'common', 'copied', 'Скопировано!'),
('ru', 'proxies', 'title', 'HTTP Прокси'),
('ru', 'proxies', 'description', 'Управление легкими HTTP-прокси через 3proxy'),
('ru', 'proxies', 'username', 'Имя пользователя'),
('ru', 'proxies', 'password', 'Пароль'),
('ru', 'proxies', 'server', 'Сервер'),
('ru', 'proxies', 'port', 'Порт'),
('ru', 'proxies', 'status', 'Статус'),
('ru', 'proxies', 'traffic', 'Трафик'),
('ru', 'proxies', 'created', 'Создан'),
('ru', 'proxies', 'actions', 'Действия'),
('ru', 'proxies', 'create', 'Создать прокси'),
('ru', 'proxies', 'pause', 'Пауза'),
('ru', 'proxies', 'resume', 'Возоновить'),
('ru', 'proxies', 'delete', 'Удалить'),
('ru', 'proxies', 'delete_confirm', 'Удалить этого прокси-пользователя навсегда?'),
('ru', 'proxies', 'no_proxies', 'Прокси пока нет'),
('ru', 'proxies', 'generate', 'Генерировать'),
('ru', 'proxies', 'leave_blank_auto', 'Оставьте пустым для автогенерации'),
('ru', 'form', 'select_server', 'Выберите сервер'),
('ru', 'proxies', 'active', 'Активен'),
('ru', 'proxies', 'paused', 'Приостановлен'),
('ru', 'proxies', 'error', 'Ошибка'),
('ru', 'menu', 'proxies', 'Прокси')
ON DUPLICATE KEY UPDATE translation=VALUES(translation);
